import 'package:nagad_clone/models/transactions.dart';

List<Transactions> allTransactionList = [
  // must add "TransactionsYear.JANUARY" in each Transctions!!!

  // january month (remove after testing)
  Transactions(
    tId: '71S4XL8W', //Must be eight digit code hobe
    tIcon: "assets/ic_transactions_out.png",
    tTitle: "Send Money",
    tBody: "01892-018369",
    tTime: "Today, 05:32 PM",
    tAmt: "19,380.00",
    tAmtIcon: "assets/ic_transactions_out_taka.png",
    tType: "OUT",
    year: TransactionsYear.JANUARY,
  ),
  //#################################################################
  Transactions(
    tId: '71S4XL8W', //Must be eight digit code hobe
    tIcon: "assets/ic_transactions_out.png",
    tTitle: "Send Money",
    tBody: "01892-018369",
    tTime: "Today, 05:32 PM",
    tAmt: "19,380.00",
    tAmtIcon: "assets/ic_transactions_out_taka.png",
    tType: "OUT",
    year: TransactionsYear.DECEMBER,
  ),
  Transactions(
    tId: '71YhK4ER',
    tIcon: "assets/ic_transactions_out.png",
    tTitle: "Send Money",
    tBody: "01747-025036",
    tTime: "Dec 20, 04:26 PM",
    tAmt: "375",
    tAmtIcon: "assets/ic_transactions_out_taka.png",
    tType: "OUT",
    year: TransactionsYear.DECEMBER,
  ),
  Transactions(
    tId: '71RD8W5N',
    tIcon: "assets/ic_transactions_out.png",
    tTitle: "Send Money",
    tBody: "01644-476942",
    tTime: "Dec 18, 02:50 PM",
    tAmt: "17,708.61",
    tAmtIcon: "assets/ic_transactions_out.png",
    tType: "OUT",
    year: TransactionsYear.DECEMBER,
  ),
  Transactions(
    tId: '0',
    tIcon: "assets/ic_transactions_out.png",
    tTitle: "Cash Out",
    tBody: "01758-684254",
    tTime: "Dec 17, 04:51 PM",
    tAmt: "600",
    tAmtIcon: "assets/ic_transactions_out_taka.png",
    tType: "OUT",
    year: TransactionsYear.DECEMBER,
  ),
  Transactions(
    tId: '0',
    tIcon: "assets/ic_transactions_out.png",
    tTitle: "Cash Out Fee",
    tBody: "#71JJ9E6L",
    tTime: "Dec 17, 02:40 PM",
    tAmt: "9",
    tAmtIcon: "assets/ic_transactions_out_taka.png",
    tType: "OUT",
    year: TransactionsYear.DECEMBER,
  ),
  Transactions(
    tId: '0',
    tIcon: "assets/ic_transactions_in.png",
    tTitle: "Bank to Nagad",
    tBody: "#71JBD96A",
    tTime: "Dec 15, 11:07 AM",
    tAmt: "500",
    tAmtIcon: "assets/ic_transactions_in_taka.png",
    tType: "IN",
    year: TransactionsYear.DECEMBER,
  ),
  Transactions(
    tId: '0',
    tIcon: "assets/ic_transactions_out.png",
    tTitle: "Mobile Recharge",
    tBody: "Ammu",
    tTime: "Dec 11, 10:27 AM",
    tAmt: "36",
    tAmtIcon: "assets/ic_transactions_out_taka.png",
    tType: "OUT",
    year: TransactionsYear.DECEMBER,
  ),
  Transactions(
    tId: '0',
    tIcon: "assets/ic_transactions_out.png",
    tTitle: "Mobile Recharge",
    tBody: "Ammu",
    tTime: "Dec 5, 08:17 AM",
    tAmt: "27",
    tAmtIcon: "assets/ic_transactions_out_taka.png",
    tType: "OUT",
    year: TransactionsYear.DECEMBER,
  ),
  Transactions(
    tId: '0',
    tIcon: "assets/ic_transactions_out.png",
    tTitle: "Bill Pay",
    tBody: "PUTW IT",
    tTime: "Dec 4, 08:15 AM",
    tAmt: "525",
    tAmtIcon: "assets/ic_transactions_out_taka.png",
    tType: "OUT",
    year: TransactionsYear.DECEMBER,
  ),
  Transactions(
    tId: '0',
    tIcon: "assets/ic_transactions_in.png",
    tTitle: "Bank to Nagad",
    tBody: "#71J7FQ4U",
    tTime: "Dec 1, 06:45 AM",
    tAmt: "700",
    tAmtIcon: "assets/ic_transactions_in_taka.png",
    tType: "IN",
    year: TransactionsYear.DECEMBER,
  ),
  Transactions(
    tId: '0',
    tIcon: "assets/ic_transactions_out.png",
    tTitle: "Cash Out",
    tBody: "01745-886221",
    tTime: "Dec 2, 05:20 AM",
    tAmt: "1000",
    tAmtIcon: "assets/ic_transactions_out_taka.png",
    tType: "OUT",
    year: TransactionsYear.DECEMBER,
  ),
  Transactions(
    tId: '0',
    tIcon: "assets/ic_transactions_out.png",
    tTitle: "Cash Out",
    tBody: "01935-684613",
    tTime: "Dec 2, 05:04 AM",
    tAmt: "3,000",
    tAmtIcon: "assets/ic_transactions_out_taka.png",
    tType: "OUT",
    year: TransactionsYear.DECEMBER,
  ),
];

List<Transactions> inTransactionList = [
  // january month (remove after testing)
  Transactions(
    tId: '71S4XL8W', //Must be eight digit code hobe
    tIcon: "assets/ic_transactions_out.png",
    tTitle: "Send Money",
    tBody: "01892-018369",
    tTime: "Today, 05:32 PM",
    tAmt: "19,380.00",
    tAmtIcon: "assets/ic_transactions_out_taka.png",
    tType: "OUT",
    year: TransactionsYear.JANUARY,
  ),

  //############################################################
  Transactions(
    tId: '0',
    tIcon: "assets/ic_transactions_in.png",
    tTitle: "Received Money",
    tBody: "Anik",
    tTime: "Dec 2, 04:30 AM",
    tAmt: "2050",
    tAmtIcon: "assets/ic_transactions_in_taka.png",
    tType: "IN",
    year: TransactionsYear.DECEMBER,
  ),
  Transactions(
    tId: '0',
    tIcon: "assets/ic_transactions_in.png",
    tTitle: "Cash In",
    tBody: "Sk Telecoms",
    tTime: "Aug 12, 11:27 AM",
    tAmt: "1200",
    tAmtIcon: "assets/ic_transactions_in_taka.png",
    tType: "IN",
    year: TransactionsYear.AUGUST,
  ),
  Transactions(
    tId: '0',
    tIcon: "assets/ic_transactions_in.png",
    tTitle: "Cash In",
    tBody: "Sk Telecoms",
    tTime: "Aug 12, 11:27 AM",
    tAmt: "5000",
    tAmtIcon: "assets/ic_transactions_in_taka.png",
    tType: "IN",
    year: TransactionsYear.AUGUST,
  ),
  Transactions(
    tId: '0',
    tIcon: "assets/ic_transactions_in.png",
    tTitle: "Cash In",
    tBody: "Sk Telecoms",
    tTime: "Aug 12, 11:27 AM",
    tAmt: "300",
    tAmtIcon: "assets/ic_transactions_in_taka.png",
    tType: "IN",
    year: TransactionsYear.AUGUST,
  ),
  Transactions(
    tId: '0',
    tIcon: "assets/ic_transactions_in.png",
    tTitle: "Cash In",
    tBody: "Sk Telecoms",
    tTime: "Aug 12, 11:27 AM",
    tAmt: "1500",
    tAmtIcon: "assets/ic_transactions_in_taka.png",
    tType: "IN",
    year: TransactionsYear.AUGUST,
  ),
  Transactions(
    tId: '0',
    tIcon: "assets/ic_transactions_in.png",
    tTitle: "Cash In",
    tBody: "Sk Telecoms",
    tTime: "Aug 12, 11:27 AM",
    tAmt: "3000",
    tAmtIcon: "assets/ic_transactions_in_taka.png",
    tType: "IN",
    year: TransactionsYear.AUGUST,
  ),
];

List<Transactions> outTransactionList = [
  // january month (remove after testing)
  Transactions(
    tId: '71S4XL8W', //Must be eight digit code hobe
    tIcon: "assets/ic_transactions_out.png",
    tTitle: "Send Money",
    tBody: "01892-018369",
    tTime: "Today, 05:32 PM",
    tAmt: "19,380.00",
    tAmtIcon: "assets/ic_transactions_out_taka.png",
    tType: "OUT",
    year: TransactionsYear.JANUARY,
  ),

  //############################################################
  Transactions(
    tId: '0',
    tIcon: "assets/ic_transactions_out.png",
    tTitle: "Payment",
    tBody: "Star Cineplex",
    tTime: "Aug 13, 10:29 PM",
    tAmt: "1200",
    tAmtIcon: "assets/ic_transactions_out_taka.png",
    tType: "OUT",
    year: TransactionsYear.AUGUST,
  ),
  Transactions(
    tId: '0',
    tIcon: "assets/ic_transactions_out.png",
    tTitle: "Payment",
    tBody: "Star Cineplex",
    tTime: "Aug 13, 10:29 PM",
    tAmt: "1200",
    tAmtIcon: "assets/ic_transactions_out_taka.png",
    tType: "OUT",
    year: TransactionsYear.AUGUST,
  ),
  Transactions(
    tId: '0',
    tIcon: "assets/ic_transactions_out.png",
    tTitle: "Payment",
    tBody: "Star Cineplex",
    tTime: "Aug 13, 10:29 PM",
    tAmt: "1200",
    tAmtIcon: "assets/ic_transactions_out_taka.png",
    tType: "OUT",
    year: TransactionsYear.AUGUST,
  ),
  Transactions(
    tId: '0',
    tIcon: "assets/ic_transactions_out.png",
    tTitle: "Payment",
    tBody: "Star Cineplex",
    tTime: "Aug 13, 10:29 PM",
    tAmt: "1200",
    tAmtIcon: "assets/ic_transactions_out_taka.png",
    tType: "OUT",
    year: TransactionsYear.AUGUST,
  ),
  Transactions(
      tId: '0',
      tIcon: "assets/ic_transactions_out.png",
      tTitle: "Payment",
      tBody: "Star Cineplex",
      tTime: "Aug 13, 10:29 PM",
      tAmt: "1200",
      tAmtIcon: "assets/ic_transactions_out_taka.png",
      tType: "OUT",
      year: TransactionsYear.AUGUST),
  Transactions(
      tId: '0',
      tIcon: "assets/ic_transactions_out.png",
      tTitle: "Payment",
      tBody: "Star Cineplex",
      tTime: "Aug 13, 10:29 PM",
      tAmt: "1200",
      tAmtIcon: "assets/ic_transactions_out_taka.png",
      tType: "OUT",
      year: TransactionsYear.AUGUST),
  Transactions(
      tId: '0',
      tIcon: "assets/ic_transactions_out.png",
      tTitle: "Payment",
      tBody: "Star Cineplex",
      tTime: "Aug 13, 10:29 PM",
      tAmt: "1200",
      tAmtIcon: "assets/ic_transactions_out_taka.png",
      tType: "OUT",
      year: TransactionsYear.AUGUST),
];

class LocalDatabase {
  static final String phone_number = "01814-456345";
}
